### ISSUE TITLE
Regression: Module broken for setups without grub password

### ISSUE THREAD

**Issue by baurmatt** [goldyfruit/puppet-grub2#40]
#36 introduced a change which ensures that `update-grub` gets triggered if the password file changes. This ignore the fact that the file isn't in the catalog if no password was specified.

```
mbaur@puppet-development:~ $ puppet apply --modulepath=Sources/ -e 'include grub2'
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README. at ["/home/mbaur/Sources/grub2/manifests/init.pp", 221]:["unknown", 1]
   (location: /home/mbaur/Sources/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Absolute_Path. There is further documentation for validate_legacy function in the README. at ["/home/mbaur/Sources/grub2/manifests/init.pp", 227]:["unknown", 1]
   (location: /home/mbaur/Sources/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use match expressions with Stdlib::Compat::String instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/home/mbaur/Sources/grub2/manifests/init.pp", 230]:["unknown", 1]
   (location: /home/mbaur/Sources/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README. at ["/home/mbaur/Sources/grub2/manifests/init.pp", 234]:["unknown", 1]
   (location: /home/mbaur/Sources/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README. at ["/home/mbaur/Sources/grub2/manifests/init.pp", 236]:["unknown", 1]
   (location: /home/mbaur/Sources/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Warning: This method is deprecated, please use the stdlib validate_legacy function,
                    with Stdlib::Compat::Integer. There is further documentation for validate_legacy function in the README. at ["/home/mbaur/Sources/grub2/manifests/init.pp", 255]:["unknown", 1]
   (location: /home/mbaur/Sources/stdlib/lib/puppet/functions/deprecation.rb:28:in `deprecation')
Error: Could not find resource 'File[/etc/grub.d/50_password]' in parameter 'subscribe' (file: /home/mbaur/Sources/grub2/manifests/update.pp, line: 7) on node puppet-development
```

**Comment by goldyfruit** [comment]
@baurmatt Thanks for fixing that !
